config/routes.rb
Rails.application.routes.draw do

  resources :images, except: [:index]
  get '/', to: 'images#index', as: :root

  post '/images/:id/process', to: 'images#process_image', as: :process_image

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord

  has_attached_file :file, styles: { default: '300x300#' }
  validates_attachment :file, presence: true, content_type: { content_type: /\Aimage\/.*\z/ }

  validates :name, presence: true

  before_destroy :delete_processed_image

  def process

    kernel = [
      [ 0.5 , 0.75 , 0.5 ],
      [ 0.75 , 1 , 0.75 ],
      [ 0.5 , 0.75 , 0.5 ],
    ]

    # kernel = [
    #   [ -1 , -1 , -1 ],
    #   [ -1 , 9 , -1 ],
    #   [ -1 , -1 , -1 ],
    # ]

    img_path = file.path(:default)
    img = Magick::Image.read(img_path).first

    # Получаем пиксели изображения
    pixels = img.get_pixels(0,0,img.columns,img.rows)

    # Генерируем путь и картинку "До"
    post_image_path = get_processed_file_path img_path, "_post"
    post_img = img

    # Генерируем картинку и путь "После"
    processed_image_path = get_processed_file_path img_path
    # Увеличиваем размер изображеиня, для добавления "ложной" рамки
    processed_img = img.resize(img.columns + kernel.first.count - 1 , img.rows + kernel.count - 1)

    # Создаём изображение в рамке
    processed_img.store_pixels(0,0, processed_img.columns, processed_img.rows, get_fake_pixels( kernel , img , pixels )) 
    
    pocessed_pixels = processed_img.get_pixels(0,0, processed_img.columns , processed_img.rows)
    # Применяем фильтр к изображению в рамке
    pixels  = apply_filter( kernel , processed_img , pocessed_pixels )

    # Получаем изображение без рамки
    processed_img = processed_img.resize( img.columns , img.rows )
    processed_img.store_pixels(0,0, processed_img.columns, processed_img.rows, pixels) 

    # Созраняем изображение
    processed_img.write( processed_image_path )

    # Задаём аттрибуты текущего объекта (Изображения)
    self.processed_image = processed_image_path
    self.processed_file_url = get_processed_file_url file.url(:default)

    self.save
  end

  protected 

    def get_fake_pixels ( kernel , img , pixels)
      half_kernel_width  = kernel.first.count / 2
      half_kernel_height = kernel.count / 2

      img_width = img.columns
      img_height = img.rows

      top_pixels = []

      (half_kernel_height+1).downto(2) do | i |
        #  get the top side pixels
        needle_row = pixels[((i-1)*img_width)..(img_width*i-1)]
        #  get the lef-top corner pixels
        top_pixels += needle_row[1..(half_kernel_width)].reverse
        # put the top side pixels
        top_pixels += needle_row
        # get the right-top corner pixels
        top_pixels += needle_row[(-half_kernel_width-1)..(-2)].reverse
      end

      bottom_pixels = []

      (-2).downto(-half_kernel_height-1) do | i |
        #  get the bottom side pixels
        needle_row = pixels[(img_width*i)..(img_width*(i+1)-1)]
        #  get the left-bottom corner pixels
        bottom_pixels += needle_row[1..(half_kernel_width)].reverse
        # put the bottom side pixels
        bottom_pixels += needle_row
        # get the right-botom pixels
        bottom_pixels += needle_row[(-half_kernel_width-1)..(-2)].reverse
      end


      # inserting left and right side pixels
      for i in 0..(img_height-1) do
        pixels_row = pixels[(i*(img_width + half_kernel_width*2))..(i*(img_width + half_kernel_width*2)+img_width-1)]

        left_inserted_pixels  = pixels_row[1..half_kernel_width].reverse
        
        right_inserted_pixels = pixels_row[(-half_kernel_width-1)..(-2)].reverse
        
        pixels.insert(i*(img_width + half_kernel_width*2), *left_inserted_pixels)
        pixels.insert(i*(img_width + half_kernel_width*2)+half_kernel_width+img_width, *right_inserted_pixels)
      end

      pixels = top_pixels + pixels
      pixels = pixels + bottom_pixels
    end

    def apply_filter ( kernel , img , pixels )
      img_width = img.columns
      img_height = img.rows

      half_kernel_width  = kernel.first.count / 2
      half_kernel_height = kernel.count / 2

      output_pixels = []
      pixel = nil


      for y in half_kernel_height..(img_height - 1 - half_kernel_height) do
        for x in half_kernel_width..(img_width - 1 - half_kernel_width) do
            rSum = gSum = bSum = kSum = 0

            for j in 0..(half_kernel_height*2) do
              for i in 0..(half_kernel_width*2) do
                pixel_pos_x = x + i - half_kernel_width
                pixel_pos_y = y + j - half_kernel_height

                pixel = pixels[ pixel_pos_y * img_width + pixel_pos_x ]

                kernel_val = kernel[i][j]

                rSum += kernel_val * pixel.red
                gSum += kernel_val * pixel.green
                bSum += kernel_val * pixel.blue

                kSum += kernel_val
              end
            end
              pixel = pixels[ y * img_width + x ]

            kSum = 1 if kSum <= 0

            rSum /= kSum 
            rSum = 0 if rSum < 0
            rSum = 65535 if rSum > 65535

            gSum /= kSum 
            gSum = 0 if gSum < 0
            gSum = 65535 if gSum > 65535

            bSum /= kSum 
            bSum = 0 if bSum < 0
            bSum = 65535 if bSum > 65535

            pixel.red   = rSum
            pixel.green = gSum
            pixel.blue  = bSum

            output_pixels << pixel 
          end
        end
      return output_pixels
    end

    def get_processed_file_path ( img_path , prefix = "_processed" )
      img_folder = img_path.split('/')
      img_folder.delete img_folder.last
      img_folder = img_folder.join('/') + "/"

      processed_file_name = img_path.split('/').last.split('.')
      processed_file_name[0] += prefix
      processed_file_name = processed_file_name.join('.')

      processed_file_path = img_folder + processed_file_name 
    end

    def get_processed_file_url ( img_url, prefix = "_processed" )
      img_folder = img_url.split('/')
      img_folder.delete img_folder.last
      img_folder = img_folder.join('/') + "/"

      processed_file_name = img_url.split('/').last.split('.')
      processed_file_name[0] += prefix
      processed_file_name = processed_file_name.join('.')

      processed_file_path = img_folder + processed_file_name 
    end

    def delete_processed_image
      File.delete(processed_image) if !processed_image.nil? && File.exist?(processed_image)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def index
    @images = Image.all
  end 

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)
    if @image.save
      flash['success'] = 'Изображение успешно создано'
      redirect_to action: :index
    else
      render :new
    end
  end

  def edit
    @image = Image.find_by(id: params[:id])
    unless @image
      flash[:dnager] = "Изображение не наидено"
      redirect_to action: :index
    end
  end

  def update
    @image = Image.find_by(id: params[:id])
    if @image.update_attributes(image_params)
      redirect_to action: :index
    else
      render :edit
    end
  end

  def destroy
    @image = Image.find_by(id: params[:id])
    if @image.destroy
      flash[:success] = "Изображение успешно удалено"
    else
      flash[:danger] = "Изображение не наидено"
    end
    redirect_to action: :index
  end

  def process_image
    image = Image.find_by(id: params[:id])
    if image
      image.process
      flash[:success] = "Изображение успешно обработано"
      redirect_to request.referer
    else
      redirect_to request.referer
      flash[:danger] = "Изображение не наидено"
    end
  end

  private

    def image_params
      params.require(:image).permit(:name, :file)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/edit.slim
.jumbotron
  h3 Редакрировать изображение
  
  = render partial: 'images/partials/form', locals: { image: @image } 
  

app/views/images/index.slim
- @images.each do |image|
  = render partial: 'images/partials/image_list_item', locals: {image: image}
- unless @images.present?
  h2
    | Ни одного изоражения не наидено, но вы можете
    =<> link_to 'создать', new_image_path
    | новое

app/views/images/new.slim
.jumbotron
  h3 Добваить изображение
  
  = render partial: 'images/partials/form', locals: { image: @image } 

app/views/images/partials/_form.slim
= simple_form_for image, wrapper: :vertical_input_group, html: { id: 'image_form' } do |form|

  - if form.error_notification
    .alert.alert-danger[role="alert"]
      = form.error_notification


  .form-inputs
    = form.input :name
    .container.col-md-12#image_file_pic_container style=(image.file.exists? ? '' : 'display: none')
      = image_tag (image.file.exists? ? image.file.url(:default) : ''), alt: 'Изображение, которое будет сохранено', class: 'dynamic-image'

    = form.input :file, as: :file
    = form.button :submit

app/views/images/partials/_image_list_item.slim
.row.col-sm-6.col-md-4
  .thumbnail
    = link_to edit_image_path(image), class: "thumbnail #{(image.processed_image.present? ? 'with_fade' : '')}"  do
      = image_tag image.file.url(:default), alt: image.name
      - if image.processed_image.present?
        = image_tag image.processed_file_url, alt: image.name, class: 'processed_image'

    .caption
      h3 #{image.name}
      p
        = link_to 'Обработать иображение', process_image_path(image), method: :post
      p
        = link_to 'Редактировать изображение', edit_image_path(image)
      p
        = link_to 'Удалить иображение', image_path(image), method: :delete, data: { confirm: 'Вы уверены, что хотите удалить изображение?'}

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Aiiro
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .container
      = render partial: 'shared/header'
      = render partial: 'shared/flashes'
      = yield

app/views/shared/_flashes.slim
- flash.each do |flash_key, flash_message|
  div class =('alert alert-' + flash_key) role="alert"
    = flash_message
  

app/views/shared/_header.slim
nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      = link_to 'Матричный фильтр', root_path, class: 'navbar-brand'
    ul.nav.navbar-nav
      li
        = link_to 'Добавить изображение', new_image_path